# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Deepak Sivashankaran
description: "Hi I'm Deepak Sivashankaran, a Data Scientist.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: <span style="color:#06f5a9";font-weight = bold; font-family = 'Roboto'> Data Science </span>
subtitle: <span style="color:#8906f5"> Portfolio </span>
location: "Coventry, UK"
resume_url: <span style = /docs/Deepak_CV.docx
avatar_image: /img/profile_picture.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/deepak-sivashankaran-54a950119/"
github: "https://github.com/Deepak-Sivashankaran" 

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

